### ISSUE TITLE
A clarification on the notes

### ISSUE THREAD

**Issue by nquesada** [gecrooks/on_gates#20]
When you write `~\pageref{accidental}` what do you mean? Is this different from a missing citation?

You use it for example in `ChBloch.tex` as:

https://github.com/gecrooks/on_gates/blob/a9bf80fe8138dddcf39ba0cac0f79a4de41f6b46/on_gates_src/ChBloch.tex#L114

Anyways, thanks for putting together this wonderful resource!

**Comment by gecrooks** [comment]
Thanks. A dangling reference left over from some material I removed.

**Comment by nquesada** [comment]
Not quite sure I get what you mean. Does this mean these `\pageref`s should be removed?

**Comment by nquesada** [comment]
Does that mean that all the `\pageref`s that currently don't resolve (and end up marked as ?) Should be removed?

**Comment by gecrooks** [comment]
This essay is a work in progress, and probably always will be since I've moved on to other projects. As a result there are a bunch of dangling references. Some, like this one, are to material I never got around to writing, and should be commented out. But others are probably just broken and should be fixed.

**Comment by nquesada** [comment]
Thanks. Sorry if my comment sounded judgemental. I think this is a fantastic resource and was trying to figure out how to best contribute to it. Anyways, if something comes to mind, do let me know.

**Comment by gecrooks** [comment]
Not at all. Contributions large or small more than welcome.
